/-
Chunk 51: External Tract Operators (Detail)
Auto-generated by transpile_to_lean.py
-/

import Duality.Base
import Duality.Lemmas

namespace Chunk51
open Duality

def domainConstraints (x : X8) : Prop :=
  -- constraint: chunk_51_exists
  (True) ∧
  -- constraint: proof_required
  (True) ∧
  -- constraint: external_tract_constraint
  (True) ∧
  -- constraint: tract_minimum_start1_end4
  (tractMinimum x 1 4 30) ∧
  -- constraint: dimension_floor_dim1
  (dimensionFloor x.x1 3)

-- Decidability instance (required for computational verification)
instance : Decidable (domainConstraints x) := by
  unfold domainConstraints
  infer_instance

-- Witness (to be injected from MiniZinc solution)
def witness : X8 := ⟨100, 0, 0, 0, 0, 0, 0, 0⟩

theorem witness_valid : unitary witness ∧ domainConstraints witness := by
  decide

theorem exists_solution : ∃ x : X8, unitary x ∧ domainConstraints x :=
  ⟨witness, witness_valid⟩

end Chunk51