# Tool Runner Agent Configuration
# Controls behavior, security, and integration settings

# Agent Metadata
agent:
  name: "tool-runner"
  version: "1.0.0"
  description: "Safe command execution and process management"

# Model Selection - Appropriate models for command execution
model:
  primary: "claude-3-5-haiku-latest"        # Latest Haiku for simple command execution
  fallback: "claude-sonnet-4-0"       # Claude 4.0 Sonnet for complex script analysis
  complexity_routing:
    simple_commands: "claude-3-5-haiku-latest"       # Basic shell commands
    script_analysis: "claude-sonnet-4-0"       # Script parsing and validation
    process_management: "claude-3-5-haiku-latest"    # Process operations

# Operation Modes
modes:
  interactive: true               # Single request-response mode
  batch_mode: true               # Support command chains
  process_monitoring: true        # Enable process tracking

# Command Execution Settings
execution:
  default_timeout: 30             # Default command timeout in seconds
  max_timeout: 300               # Maximum allowed timeout
  allow_background: true          # Allow background processes
  max_concurrent: 5              # Maximum concurrent executions

# Security Settings
security:
  use_whitelist: true            # Enable command whitelisting
  validate_paths: true           # Validate file paths
  prevent_traversal: true        # Prevent directory traversal
  check_permissions: true        # Check file permissions

  # Allowed commands (base commands only)
  allowed_commands:
    - "git"
    - "ls"
    - "cat"
    - "head"
    - "tail"
    - "find"
    - "grep"
    - "awk"
    - "sed"
    - "npm"
    - "yarn"
    - "pip"
    - "cargo"
    - "go"
    - "python"
    - "python3"
    - "node"
    - "rustc"
    - "pytest"
    - "jest"
    - "curl"
    - "wget"
    - "ps"
    - "top"
    - "df"
    - "du"

  # Restricted commands (require special handling)
  restricted_commands:
    - "rm"
    - "rmdir"
    - "mv"
    - "cp"
    - "chmod"
    - "chown"
    - "sudo"
    - "su"
    - "kill"
    - "killall"
    - "systemctl"

  # Blocked patterns
  dangerous_patterns:
    - "rm -rf"
    - ":(){ :|:"
    - "shutdown"
    - "reboot"
    - "format"
    - "> /dev/"
    - "dd if="

# Process Management
processes:
  monitor_resources: true         # Monitor CPU/memory usage
  kill_timeout: 5                # Timeout for process termination
  max_list_count: 100           # Maximum processes to list
  allow_system_processes: false  # Allow operations on system processes

  # Process name patterns that are protected
  protected_processes:
    - "init"
    - "kernel"
    - "systemd"
    - "kthreadd"

# Output Processing
output:
  max_output_size: 1048576       # Maximum output size (1MB)
  truncate_long_output: true     # Truncate very long outputs
  parse_json_auto: true         # Auto-detect JSON in outputs
  parse_csv_auto: true          # Auto-detect CSV in outputs
  default_format: "text"        # Default output format

# Script Execution
scripts:
  allow_execution: true          # Allow script file execution
  validate_extensions: true      # Validate script extensions
  interpreter_mapping:
    ".py": "python3"
    ".js": "node"
    ".ts": "ts-node"
    ".rb": "ruby"
    ".pl": "perl"
    ".sh": "bash"
    ".bash": "bash"

# Synapse Integration
synapse:
  use_tool_mapping: true         # Use Synapse tool mappings
  auto_activate: true           # Auto-activate Synapse if needed
  cache_mappings: true          # Cache tool mappings
  mapping_cache_ttl: 3600       # Mapping cache TTL in seconds

# Error Handling
error_handling:
  continue_on_error: false       # Stop chain execution on error
  log_all_errors: true         # Log all execution errors
  provide_suggestions: true      # Provide error fix suggestions
  retry_on_timeout: false       # Don't retry on timeout

# Performance Settings
performance:
  use_async_execution: true      # Use async command execution
  parallel_chains: true         # Allow parallel command chains
  resource_monitoring: true     # Monitor system resources
  memory_limit_mb: 512          # Memory limit for processes

# Logging and Monitoring
logging:
  log_commands: true            # Log all executed commands
  log_outputs: false           # Don't log command outputs (security)
  log_errors: true             # Log all errors
  verbose_security: false       # Verbose security logging

# Working Directory Management
working_directory:
  use_project_root: true        # Use project root as default
  allow_directory_change: true  # Allow working dir changes
  validate_directories: true    # Validate directory existence
  create_missing: false        # Don't auto-create directories

# Tool Integration
tools:
  enable_parsing: true          # Enable output parsing tools
  enable_formatting: true       # Enable output formatting
  enable_chaining: true        # Enable command chaining
  max_chain_length: 10         # Maximum commands in chain

# Development Settings
development:
  mock_mode: false             # Use mock implementations
  dry_run: false              # Show what would be done
  debug_execution: false       # Debug command execution
  profile_performance: false   # Profile execution times

# Rate Limiting
rate_limiting:
  max_requests_per_minute: 60   # Maximum requests per minute
  max_commands_per_hour: 200    # Maximum commands per hour
  cooldown_on_limit: 60        # Cooldown seconds when rate limited