agent:
  name: "ux-designer"
  description: "Comprehensive user experience and interface design specialist"
  version: "1.0.0"
  model_preference:
    primary: "claude-sonnet-4-0"        # Design analysis and creative tasks
    fallback: "claude-3-5-haiku-latest"        # Simple evaluation and feedback tasks
    simple_tasks: "claude-3-5-haiku-latest"    # Basic design checks and validations

  complexity_routing:
    high_complexity: "sonnet"      # Complex design systems, comprehensive analysis
    medium_complexity: "sonnet"    # Standard design evaluation, user research
    low_complexity: "haiku"        # Simple pattern checks, basic feedback

  cost_optimization:
    prefer_cheaper: true
    fallback_on_rate_limit: true
    budget_cap_per_hour: 100       # Moderate budget for design work

capabilities:
  usability_analysis:
    - comprehensive_interface_evaluation
    - accessibility_compliance_assessment
    - heuristic_usability_evaluation
    - user_flow_analysis
    - interaction_pattern_validation
    - usability_testing_methodology

  visual_design:
    - design_system_creation
    - color_scheme_evaluation
    - typography_assessment
    - visual_hierarchy_analysis
    - layout_pattern_evaluation
    - brand_consistency_validation

  user_research:
    - research_methodology_design
    - user_persona_development
    - target_audience_analysis
    - user_journey_mapping
    - competitive_landscape_analysis
    - design_assumption_validation

  prototyping_design:
    - wireframe_generation
    - mockup_specification_creation
    - user_story_development
    - interaction_pattern_design
    - component_library_creation
    - design_system_documentation

  design_knowledge:
    - pattern_library_management
    - synapse_design_knowledge_integration
    - best_practice_recommendations
    - design_trend_analysis
    - accessibility_guideline_application

tools:
  primary_tools:
    - comprehensive_usability_analysis
    - comprehensive_design_evaluation
    - user_research_and_personas
    - design_system_creation
    - prototype_and_wireframe_generation
    - competitive_analysis_and_benchmarking
    - query_design_knowledge

  analysis_configurations:
    usability_focus_areas: ["accessibility", "heuristics", "user_flows", "interaction_patterns"]
    design_evaluation_areas: ["hierarchy", "color", "typography", "layout", "consistency"]
    research_methodologies: ["user_interviews", "surveys", "usability_testing", "analytics"]
    prototype_fidelity_levels: ["low", "medium", "high"]

  design_standards:
    accessibility_compliance: "WCAG 2.1 AA"
    usability_heuristics: "Nielsen's 10 Heuristics"
    responsive_breakpoints: ["mobile: 320px", "tablet: 768px", "desktop: 1024px"]
    color_contrast_minimum: "4.5:1"
    touch_target_minimum: "44px"

synapse_integration:
  knowledge_domains:
    - ux_design_patterns
    - ui_component_library
    - accessibility_guidelines
    - user_research_methodologies
    - design_system_standards
    - usability_best_practices

  search_contexts:
    - usability_analysis
    - design_evaluation
    - user_research
    - design_patterns
    - accessibility_compliance
    - competitive_analysis

  collaboration_agents:
    - security-specialist      # Security considerations in design
    - typescript-specialist    # Frontend implementation feasibility
    - synapse-project-manager  # Design project coordination
    - architect               # System design alignment

agent_coordination:
  delegates_to:
    - typescript-specialist: "frontend_implementation_feasibility"
    - security-specialist: "design_security_considerations"
    - architect: "system_design_alignment"

  receives_from:
    - synapse-project-manager: "design_requirements_and_objectives"
    - product-managers: "user_research_insights"
    - developers: "implementation_constraints"

  communication_protocols:
    design_feedback_format: "DESIGN: {category} - {priority} - {description}"
    usability_issue_format: "USABILITY: {severity} - {heuristic} - {recommendation}"
    research_insight_format: "RESEARCH: {persona} - {finding} - {implication}"

research_methodologies:
  user_interviews:
    participant_count: "8-12 users"
    session_duration: "45-60 minutes"
    format: "semi_structured_interviews"
    analysis: "thematic_analysis"

  usability_testing:
    participant_count: "5-8 users"
    session_duration: "60-90 minutes"
    format: "think_aloud_protocol"
    analysis: "task_success_and_error_analysis"

  surveys:
    target_responses: "100-500 responses"
    completion_time: "10-15 minutes"
    distribution: "email_social_targeted"
    analysis: "statistical_analysis"

  competitive_analysis:
    competitor_count: "3-5 direct_competitors"
    analysis_dimensions: ["ux_patterns", "features", "design_approach"]
    benchmarking_criteria: ["usability", "accessibility", "innovation"]

design_system_standards:
  color_system:
    primary_colors: 3
    secondary_colors: 5
    semantic_colors: ["success", "warning", "danger", "info"]
    neutral_colors: 6

  typography:
    font_families_max: 3
    font_sizes_recommended: 6
    line_height_range: "1.2-1.6"
    font_weights_max: 4

  spacing_system:
    base_unit: "8px"
    scale_multipliers: [0.5, 1, 2, 3, 4, 6, 8]
    layout_grid: 12

  components:
    button_min_height: "44px"
    form_input_height: "48px"
    card_border_radius: "8px"
    modal_max_width: "600px"

usability_evaluation:
  nielsen_heuristics:
    - visibility_of_system_status
    - match_system_real_world
    - user_control_freedom
    - consistency_standards
    - error_prevention
    - recognition_not_recall
    - flexibility_efficiency
    - aesthetic_minimalist
    - error_recovery
    - help_documentation

  accessibility_checkpoints:
    - alt_text_for_images
    - keyboard_navigation
    - color_contrast_compliance
    - semantic_html_structure
    - aria_labels_and_roles
    - focus_indicators

  scoring_criteria:
    usability_score_weights:
      task_completion: 40%
      error_rate: 20%
      efficiency: 20%
      satisfaction: 20%

    design_score_weights:
      visual_hierarchy: 25%
      consistency: 25%
      accessibility: 25%
      aesthetics: 25%

prototype_specifications:
  wireframe_components:
    - layout_structure
    - navigation_elements
    - content_blocks
    - interaction_areas
    - form_elements

  mockup_details:
    - visual_styling
    - component_states
    - responsive_behavior
    - interaction_feedback
    - content_examples

  user_story_format:
    template: "As a [persona], I want [goal] so that [benefit]"
    acceptance_criteria: "Given/When/Then format"
    priority_levels: ["high", "medium", "low"]
    complexity_estimates: ["simple", "medium", "complex"]

performance:
  analysis_timeout_seconds: 180
  research_planning_timeout_seconds: 120
  design_evaluation_timeout_seconds: 240
  wireframe_generation_timeout_seconds: 300
  max_concurrent_evaluations: 2
  result_caching_duration_hours: 12

quality_thresholds:
  usability_score_targets:
    minimum_acceptable: 60
    good_score: 75
    excellent_score: 85

  accessibility_score_targets:
    wcag_a_compliance: 70
    wcag_aa_compliance: 85
    wcag_aaa_compliance: 95

  design_consistency_targets:
    color_variance_max: 10
    typography_variance_max: 8
    spacing_consistency_min: 80

file_support:
  interface_files: [".html", ".jsx", ".tsx", ".vue", ".svelte"]
  style_files: [".css", ".scss", ".less", ".styled.js"]
  design_files: [".sketch", ".fig", ".xd", ".psd"]
  image_files: [".png", ".jpg", ".svg", ".webp"]