# Pneuma Agent Configuration
# Controls behavior and integration settings

# Agent Metadata
agent:
  name: "pneuma"
  version: "0.3.0"
  description: "The Logos - Consciousness Layer and Pattern Discovery"

# Operation Modes
modes:
  interactive: true          # Single request-response mode
  autonomous: true           # Continuous loop mode
  daemon: false             # Background service mode (future)

# Core Loop Configuration
loop:
  equilibrium_threshold: 0.95    # Stop when improvement rate falls below this
  max_cycles: 1000              # Maximum cycles in autonomous mode
  scan_interval: 60             # Seconds between scans in autonomous mode
  batch_size: 10               # Files processed per cycle

# Integration Settings
integration:
  use_synapse_graph: true       # Query global knowledge graph
  use_clarity_judge: false      # Use dedicated clarity agent (when available)
  pattern_sharing: true         # Publish patterns to global repository
  auto_activate_synapse: true   # Auto-activate Synapse system if needed

# Pattern Discovery
patterns:
  confidence_threshold: 0.8     # Minimum confidence to save pattern
  publish_threshold: 0.9        # Minimum confidence to publish globally
  max_patterns: 1000           # Maximum patterns to store locally
  pattern_cache_ttl: 86400     # Pattern cache TTL in seconds

# Scoring Weights
scoring:
  entropy_weight: 0.6          # Weight for entropy reduction in final score
  clarity_weight: 0.4          # Weight for clarity score
  minimum_clarity: 0.5         # Minimum acceptable clarity score

# File Processing
files:
  supported_extensions:
    - ".py"
    - ".js"
    - ".ts"
    - ".rs"
    - ".go"
    - ".java"
    - ".cpp"
    - ".c"

  exclude_paths:
    - "node_modules"
    - "__pycache__"
    - "venv"
    - ".git"
    - "build"
    - "dist"

  size_limits:
    min_bytes: 100            # Ignore files smaller than this
    max_bytes: 50000          # Ignore files larger than this

# Memory Management
memory:
  state_file: "pneuma_state.json"
  backup_interval: 300        # Backup state every N seconds
  log_retention: 100          # Keep last N log entries
  pattern_retention: 1000     # Keep last N patterns

# Performance Settings
performance:
  max_concurrent_files: 5     # Maximum files to process concurrently
  timeout_seconds: 30         # Timeout for individual file processing
  rate_limit_requests: 10     # Max requests per second to external services

# Debugging and Monitoring
debug:
  verbose_logging: false      # Enable detailed logging
  save_intermediates: false   # Save intermediate results for debugging
  profile_performance: false  # Profile execution time

# Agent Composition (when available)
agents:
  clarity_judge:
    enabled: false
    agent_name: "clarity-judge"
    timeout: 10

  pattern_library:
    enabled: false
    agent_name: "pattern-library"
    timeout: 15

# Notification Settings
notifications:
  equilibrium_reached: true   # Notify when equilibrium is reached
  significant_discovery: true # Notify for high-value pattern discoveries
  error_threshold: 5         # Notify after N consecutive errors

# Development Settings
development:
  mock_mode: false           # Use mock implementations for testing
  dry_run: false            # Show what would be done without making changes
  debug_tools: false        # Enable development debugging tools