-- This module serves as the root of the `Duality` library.
-- Import base module and all 62 formalized chunks from TRUE_DUAL_TRACT
import Duality.Base
import Duality.Transpiler
import Duality.Chunks.Chunk01
import Duality.Chunks.Chunk02
import Duality.Chunks.Chunk03
import Duality.Chunks.Chunk04
import Duality.Chunks.Chunk05
import Duality.Chunks.Chunk06
import Duality.Chunks.Chunk07
import Duality.Chunks.Chunk08
import Duality.Chunks.Chunk09
import Duality.Chunks.Chunk10
import Duality.Chunks.Chunk11
import Duality.Chunks.Chunk12
import Duality.Chunks.Chunk13
import Duality.Chunks.Chunk14
import Duality.Chunks.Chunk15
import Duality.Chunks.Chunk16
import Duality.Chunks.Chunk17
import Duality.Chunks.Chunk18
import Duality.Chunks.Chunk19
import Duality.Chunks.Chunk20
import Duality.Chunks.Chunk21
import Duality.Chunks.Chunk22
import Duality.Chunks.Chunk23
import Duality.Chunks.Chunk24
import Duality.Chunks.Chunk25
import Duality.Chunks.Chunk26
import Duality.Chunks.Chunk27
import Duality.Chunks.Chunk28
import Duality.Chunks.Chunk29
import Duality.Chunks.Chunk30
import Duality.Chunks.Chunk31
import Duality.Chunks.Chunk32
import Duality.Chunks.Chunk33
import Duality.Chunks.Chunk34
import Duality.Chunks.Chunk35
import Duality.Chunks.Chunk36
import Duality.Chunks.Chunk37
import Duality.Chunks.Chunk38
import Duality.Chunks.Chunk39
import Duality.Chunks.Chunk40
import Duality.Chunks.Chunk41
import Duality.Chunks.Chunk42
import Duality.Chunks.Chunk43
import Duality.Chunks.Chunk44
import Duality.Chunks.Chunk45
import Duality.Chunks.Chunk46
import Duality.Chunks.Chunk47
import Duality.Chunks.Chunk48
import Duality.Chunks.Chunk49
import Duality.Chunks.Chunk50
import Duality.Chunks.Chunk51
import Duality.Chunks.Chunk52
import Duality.Chunks.Chunk53
import Duality.Chunks.Chunk54
import Duality.Chunks.Chunk55
import Duality.Chunks.Chunk56
import Duality.Chunks.Chunk57
import Duality.Chunks.Chunk58
import Duality.Chunks.Chunk59
import Duality.Chunks.Chunk60
import Duality.Chunks.Chunk61
import Duality.Chunks.Chunk62

-- Test suite
import Duality.Tests
