# File Creator Agent Configuration
# Controls behavior and integration settings

# Agent Metadata
agent:
  name: "file-creator"
  version: "1.0.0"
  description: "Template-driven file and directory creation"

# Model Selection - Haiku for simple file operations
model:
  primary: "claude-3-5-haiku-latest"        # Simple file operations
  fallback: "claude-sonnet-4-0"      # Complex template processing
  complexity_routing:
    simple_create: "haiku"         # Basic file creation
    template_processing: "sonnet"  # Template variable processing
    batch_operations: "haiku"      # Multiple file creation

# Operation Modes
modes:
  interactive: true               # Single request-response mode
  batch_mode: true               # Support batch operations
  template_mode: true            # Template processing enabled

# File Creation Settings
files:
  overwrite_protection: true      # Never overwrite existing files
  create_parent_dirs: true        # Auto-create parent directories
  backup_on_conflict: false       # Don't backup conflicting files

  # Supported file types for template processing
  template_extensions:
    - ".md"
    - ".py"
    - ".ts"
    - ".tsx"
    - ".js"
    - ".jsx"
    - ".rs"
    - ".go"
    - ".java"
    - ".cpp"
    - ".c"
    - ".html"
    - ".css"
    - ".yml"
    - ".yaml"
    - ".json"

  # Default permissions
  file_permissions: 644
  dir_permissions: 755

# Template Configuration
templates:
  use_synapse_templates: true      # Query Synapse for templates
  fallback_to_local: true         # Use local templates if Synapse fails
  cache_templates: true           # Cache frequently used templates
  cache_ttl: 3600                 # Template cache TTL in seconds

  # Default template variables
  default_variables:
    CURRENT_DATE: true            # Auto-inject current date
    PROJECT_ROOT: true            # Auto-inject project root path
    USER_NAME: false              # Don't auto-inject user name

# Synapse Integration
synapse:
  auto_activate: true             # Auto-activate Synapse if needed
  search_templates: true          # Search for templates in knowledge graph
  search_patterns: true           # Search for file structure patterns
  timeout: 30                     # Synapse query timeout in seconds

# Batch Operations
batch:
  max_files_per_batch: 50         # Maximum files in single batch
  parallel_creation: true         # Create files in parallel
  max_concurrent: 5               # Maximum concurrent operations
  fail_fast: false               # Continue on individual failures

# Directory Structure Creation
directories:
  create_nested: true             # Support nested directory creation
  template_driven: true           # Use templates for directory structures
  maintain_permissions: true      # Preserve directory permissions

# Error Handling
error_handling:
  continue_on_error: true         # Continue batch on individual errors
  log_errors: true               # Log all errors for debugging
  provide_suggestions: true       # Provide fix suggestions

# Performance Settings
performance:
  use_async_io: true             # Use async file operations
  buffer_size: 8192              # File I/O buffer size
  timeout_seconds: 120           # Overall operation timeout

# Output Settings
output:
  verbose_logging: false         # Detailed operation logging
  show_file_sizes: false        # Show created file sizes
  show_timestamps: false         # Show creation timestamps
  use_emojis: true              # Use emojis in status messages

# Security Settings
security:
  validate_paths: true           # Validate file paths for security
  restrict_parent_traversal: true # Prevent ../ path traversal
  allowed_path_patterns:         # Regex patterns for allowed paths
    - "^[^/].*"                 # No absolute paths starting with /
    - "^(?!.*\\.\\./)"          # No parent directory traversal

# Development Settings
development:
  mock_mode: false              # Use mock implementations
  dry_run: false               # Show what would be done without creating
  debug_templates: false        # Debug template processing